services:
  mysql:
    image: "mysql:8.0.29"
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.compose.mysql.env
    cap_add:
      - SYS_NICE
    healthcheck:
      test: 'mysql -uMYSQL_USER -pMYSQL_PASSWORD --execute "SHOW DATABASES;"'
      interval: 5s
      retries: 60

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/app:/app
    healthcheck:
      test: 'curl http://localhost:80'
      interval: 5s
      retries: 60
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./.compose.mysql.env
    healthcheck:
      test: 'curl http://localhost/api/docs'
      interval: 5s
      retries: 60

    depends_on:
      mysql:
        condition: service_healthy

  api-gateway:
    image: nginx:latest
    volumes:
      - ./api-gateway:/etc/nginx/conf.d
    ports:
      - 0.0.0.0:80:80
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy